apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mbcr68fzu-go
  janus-idp.io/tekton: mbcr68fzu-go
  backstage.io/kubernetes-id: mbcr68fzu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mbcr68fzu-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
